# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self):
        self.videoBack = None

    def setupUi(self, Form):
        Form.setObjectName("Widget")
        Form.resize(1080, 720)
        Form.setMinimumSize(QtCore.QSize(1080, 720))
        Form.setStyleSheet("\n"
                             "background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, -20, 381, 741))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/tarak/OneDrive/Desktop/ISHI Technology/IMAGES/bot.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(400, -25, 661, 171))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/tarak/OneDrive/Desktop/ISHI Technology/IMAGES/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(410, 615, 201, 100))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-image : url(C:/Users/tarak/OneDrive/Desktop/ISHI Technology/IMAGES/Login.png);\n"
                                      "background-color: transparent;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 620, 200, 100))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("border-image: url(C:/Users/tarak/OneDrive/Desktop/ISHI Technology/IMAGES/exit.png);\n"
                                        "background-color:transparent;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(400, 110, 661, 501))
        self.label_3.setStyleSheet("border-color: rgb(255, 255, 255);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "border-style:solid;\n"
                                   "border-width : 1px 1px 1px 1px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())