# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginwindowClass(object):
    def setupUi(self, LoginwindowClass):
        LoginwindowClass.setObjectName("LoginwindowClass")
        LoginwindowClass.setWindowModality(QtCore.Qt.NonModal)
        LoginwindowClass.setEnabled(True)
        LoginwindowClass.resize(1080, 720)
        LoginwindowClass.setMouseTracking(False)
        LoginwindowClass.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.ishilogo = QtWidgets.QLabel(LoginwindowClass)
        self.ishilogo.setGeometry(QtCore.QRect(330, -10, 500, 131))
        self.ishilogo.setText("")
        self.ishilogo.setPixmap(QtGui.QPixmap("C:/Users/tarak/OneDrive/Desktop/ISHI Technology/IMAGES/logo.png"))
        self.ishilogo.setScaledContents(True)
        self.ishilogo.setObjectName("ishilogo")
        self.frame = QtWidgets.QFrame(LoginwindowClass)
        self.frame.setGeometry(QtCore.QRect(30, 120, 1021, 541))
        self.frame.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "border-color: rgb(255, 255, 255);\n"
                                 "border-style:solid;\n"
                                 "border-width:5px 5px 5px 5px;\n"
                                 "border-radius: 30px\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(50, 430, 181, 91))
        self.pushButton.setStyleSheet("border-image: url(C:/Users/tarak/OneDrive/Desktop/ISHI Technology/IMAGES/retry.png)\n;"
                                      "background-color:transparent;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 430, 181, 91))
        self.pushButton_2.setStyleSheet("border-image: url(C:/Users/tarak/OneDrive/Desktop/ISHI Technology/IMAGES/back.png)\n;"
                                        "background-color:transparent;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(810, 430, 181, 91))
        self.pushButton_3.setStyleSheet("border-image: url(C:/Users/tarak/OneDrive/Desktop/ISHI Technology/IMAGES/exit.png)\n;"
                                        "background-color:transparent;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(130, 40, 761, 371))
        self.label_2.setStyleSheet("border:none;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/tarak/OneDrive/Desktop/ISHI Technology/IMAGES/Wrong Pass.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.usernameentry = QtWidgets.QLineEdit(self.frame)
        self.usernameentry.setGeometry(QtCore.QRect(330, 60, 381, 91))
        self.usernameentry.setStyleSheet("font: 30pt \"Stencil\";\n"
                                         "padding-left : 12px;")
        self.usernameentry.setObjectName("usernameentry")
        self.passwordentry = QtWidgets.QLineEdit(self.frame)
        self.passwordentry.setGeometry(QtCore.QRect(330, 190, 381, 91))
        self.passwordentry.setStyleSheet("font: 30pt \"Stencil\";\n"
                                         "padding-left : 12px;")
        self.passwordentry.setObjectName("passwordentry")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(430, 310, 181, 91))
        self.pushButton_4.setStyleSheet("border-image: url(C:/Users/tarak/OneDrive/Desktop/ISHI Technology/IMAGES/login.png)\n;"
                                        "background-color:transparent;")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.usernameentry.raise_()
        self.passwordentry.raise_()
        self.pushButton_4.raise_()
        self.label_2.raise_()

        self.retranslateUi(LoginwindowClass)
        QtCore.QMetaObject.connectSlotsByName(LoginwindowClass)

    def retranslateUi(self, LoginwindowClass):
        _translate = QtCore.QCoreApplication.translate
        LoginwindowClass.setWindowTitle(_translate("LoginwindowClass", "LoginwindowClass"))
        self.usernameentry.setPlaceholderText(_translate("LoginwindowClass", "USERNAME"))
        self.passwordentry.setPlaceholderText(_translate("LoginwindowClass", "PASSWORD"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    LoginwindowClass = QtWidgets.QWidget()
    ui = Ui_LoginwindowClass()
    ui.setupUi(LoginwindowClass)
    LoginwindowClass.show()
    sys.exit(app.exec_())
